AA-129 L-10 calling _disableInitializers() from account constructor
eth-infinitism/account-abstraction pull request #201
Opened 2023-02-02 20:11 UTC by shahafn

Currnetly failing bls account test, since it uses initalizer(), pending #195 merge

2023-02-05 13:39 UTC, forshtat requested changes

2023-02-05 13:39 UTC, forshtat commented on contracts/samples/SimpleAccount.sol
> +        _disableInitializers();
The same should be done in the BLSAccount, I assume.

2023-02-05 13:40 UTC, forshtat approved these changes, later dismissed

2023-02-08 21:52 UTC, drortirosh approved these changes

2023-02-08 21:53 UTC, merged