add postOp param (gasPrice)
eth-infinitism/account-abstraction pull request #395
Opened 2024-01-06 18:00 UTC by drortirosh

saves TokenPaymaster 731 gas (it currently required to pass maxFeePerGas and maxPriorityFee as context params)
add "plain postOp" (which ignores this param) 24 gas.

2024-01-06 21:27 UTC, yoavw approved these changes, later dismissed
Makes sense, let's do it.

2024-01-07 18:35 UTC, shahafn submitted a review, later dismissed

2024-01-08 14:07 UTC, forshtat requested changes

2024-01-08 14:07 UTC, forshtat commented on contracts/core/BasePaymaster.sol
> +        uint gasPrice
This name is highly confusing. The `postOp` method can actually call `tx.gasprice` and developers will be confused with the fact they are not the same thing. We should name it `actualUserOpFeePerGas` or something like that, so that the name "screams" that this is not `tx.gasprice`.
Also, please, use `uint256` for both params - makes no sense to use two different ways in one line.

2024-01-08 14:07 UTC, forshtat commented on contracts/samples/LegacyTokenPaymaster.sol
> +    function _postOp(PostOpMode mode, bytes calldata context, uint256 actualGasCost, uint gasPrice) internal override {
Unrelated - why do we keep this old code around? Can we remove it?

2024-01-08 14:07 UTC, forshtat commented on contracts/samples/TokenPaymaster.sol
> +            ) = abi.decode(context, (uint256, address));
This means the entire `getGasPrice` function is no longer needed - please remove.

2024-01-09 13:54 UTC, shahafn approved these changes

2024-01-09 14:08 UTC, forshtat approved these changes

2024-01-09 14:27 UTC, merged